FROM phusion/baseimage:0.9.17

# Use baseimage-docker's init system.
CMD ["/sbin/my_init"]

RUN apt-get update && apt-get -y install git-core\
    curl\
    bzip2\
    build-essential\
    libssl-dev\
    libffi-dev\
    zlib1g-dev\
    libbz2-dev\
    libreadline-dev\
    libsqlite3-dev\
    wget\
    llvm\
    libncurses5-dev\
    nginx

# ...put your own build instructions here...

WORKDIR /opt/{{user}}
RUN groupadd {{group}}
RUN useradd -m -g {{group}} {{user}}
RUN chown -R {{group}}:{{user}} /opt/{{user}}
VOLUME /opt/{{user}}/config

ENV HOME  /opt/{{user}}

# Clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
